services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: pokesocket-client:latest
    container_name: pokesocket-client
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: pokesocket-server:latest
    container_name: pokesocket-server
    ports:
      - "3003:8080"
    restart: unless-stopped
    networks:
      - app-network
    environment:
      # API
      API_PORT: "8080"
      # DB
      DB_URI: "postgresql://postgres:postgres@pokesocket-db:5432/postgres"
      # LOGGING Configuration
      LOGGING_LEVEL: "debug"
      LOGGING_PRETTY: "yes"
      # CORS Configuration
      ALLOWED_ORIGINS: "http://localhost:3001,http://localhost:3000,http://example.com"
      ALLOWED_CONTENT_TYPES: "application/json,text/plain"
      ALLOWED_METHODS: "GET,POST,PUT,DELETE,PATCH"
      ALLOWED_HEADERS: "Content-Type,Authorization"
  db:
    build:
      context: ./db/game
      dockerfile: Dockerfile
    image: postgres-cron:17
    container_name: pokesocket-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/game/migrations:/docker-entrypoint-initdb.d  # Auto-run SQL files on first start
    restart: unless-stopped

networks:
  app-network:

volumes:
  postgres_data: