name: Backend Integration Tests
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize

# Let just one instance of this action run at a time:
# Prevents redundant runs when multiple commits are pushed 
# in quick succession to the same PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lintingAndTesting:
    name: Backend checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          # ref: ${{github.event.pull_request.head.ref}}
          # repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Set up Nix
        uses: nixbuild/nix-quick-install-action@v30

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: build-${{ runner.os }}-${{ hashFiles('**/package-lock.json', 'package.json', 'flake.nix', 'flake.lock') }}
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: build-${{ runner.os }}-
          
      - name: Setup node
        run: nix develop -c moon run server:setup

      - name: Testing
        run: nix develop -c process-compose up -f process-compose.yaml -t=false

      - name: Pretty moon logs
        uses: appthrust/moon-ci-retrospect@v1
        if: success() || failure()
